{
 "title": "Component states",
 "tags": [ "as code" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster_id",
    "label": "Cluster ID",
    "query": {
     "query": "label_values(zbctrl_zbcluster_ready_state{}, cluster_id)"
    }
   },
   {
    "name": "ingress",
    "query": "operate-ingress-webapp, optimize-ingress-webapp, tasklist-ingress-webapp, zeebe-ingress"
   },
   { "name": "rate_interval", "label": "Rate Interval", "query": "2m, 5m, 30m, 1h, 12h, 1d" }
  ]
 },
 "panels": [
  { "title": "Healthiness", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Component states",
   "type": "state-timeline",
   "description": "As reported by the Zeebe operator.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "avg(zbctrl_zbcluster_ready_state{cluster_id=~\"$cluster_id\"}) by (cluster_id)",
     "legendFormat": "Overall"
    },
    {
     "expr": "avg(zbctrl_zbcluster_operate_state{cluster_id=~\"$cluster_id\"}) by (cluster_id)",
     "legendFormat": "Operate"
    },
    {
     "expr": "avg(zbctrl_zbcluster_optimize_state{cluster_id=~\"$cluster_id\"}) by (cluster_id)",
     "legendFormat": "Optimize"
    },
    {
     "expr": "avg(zbctrl_zbcluster_tasklist_state{cluster_id=~\"$cluster_id\"}) by (cluster_id)",
     "legendFormat": "Tasklist"
    },
    {
     "expr": "avg(zbctrl_zbcluster_zeebe_state{cluster_id=~\"$cluster_id\"}) by (cluster_id)",
     "legendFormat": "Zeebe"
    },
    {
     "expr": "avg(zbctrl_zbcluster_elasticsearch_state{cluster_id=~\"$cluster_id\"}) by (cluster_id)",
     "legendFormat": "Elasticsearch"
    }
   ]
  },
  {
   "title": "Elasticsearch",
   "type": "state-timeline",
   "description": "As reported by Elasticsearch itself.",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "scalar(elasticsearch_cluster_health_status{color=\"green\", namespace=~\"$cluster_id-zeebe\"}) +\nscalar(elasticsearch_cluster_health_status{color=\"yellow\", namespace=~\"$cluster_id-zeebe\"}) * 2 +\nscalar(elasticsearch_cluster_health_status{color=\"red\", namespace=~\"$cluster_id-zeebe\"}) * 3",
     "legendFormat": "Cluster health"
    }
   ]
  },
  { "title": "Availability", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Availability: $ingress",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 15 },
   "repeat": "ingress",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{ingress=\"$ingress\", exported_namespace=\"${cluster_id}-zeebe\", status!~\"^5.+\"}[$rate_interval])) by (ingress)\n/\nsum(rate(nginx_ingress_controller_requests{ingress=~\"$ingress\", exported_namespace=\"${cluster_id}-zeebe\"}[$rate_interval]) > 0) by (ingress)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Status Codes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Status Codes: $ingress",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 25 },
   "repeat": "ingress",
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(\n    rate(nginx_ingress_controller_requests{ingress=\"$ingress\", exported_namespace=\"${cluster_id}-zeebe\"}[$rate_interval])\n) by (status)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Latency: $ingress",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 34 },
   "repeat": "ingress",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(\n  rate(\n    nginx_ingress_controller_response_duration_seconds_sum{ingress=\"$ingress\", exported_namespace=\"${cluster_id}-zeebe\"}[$__rate_interval]\n  )\n) by (method)",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  }
 ]
}