{
 "title": "Camunda Cloud",
 "tags": [ "as code" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(atomix_role, namespace)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(atomix_role{namespace=~\"$namespace\"}, pod)"
    }
   },
   {
    "name": "partition",
    "query": {
     "query": "label_values(atomix_role{namespace=~\"$namespace\", pod=~\"$pod\"}, partition)"
    }
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Average Import Time - Operate",
   "type": "stat",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(operate_import_time_seconds_sum{namespace=~\"$namespace\", partition=~\"$partition\", pod=~\"$pod\"}[1m])) / sum(rate(operate_import_time_seconds_count{namespace=~\"$namespace\", partition=~\"$partition\", pod=~\"$pod\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Import Time - Tasklist",
   "type": "stat",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(tasklist_import_time_seconds_sum{namespace=~\"$namespace\", partition=~\"$partition\", pod=~\"$pod\"}[5m])) /sum(rate(tasklist_import_time_seconds_count{namespace=~\"$namespace\", partition=~\"$partition\", pod=~\"$pod\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Import Time - Optimize",
   "type": "stat",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(optimize_import_overallImportTime_seconds_sum{namespace=~\"$namespace\", partition=~\"$partition\", pod=~\"$pod\"}[5m])) /sum(rate(optimize_import_overallImportTime_seconds_count{namespace=~\"$namespace\", partition=~\"$partition\", pod=~\"$pod\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Zeebe",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Activated Processes in avg overtime per sec",
   "type": "stat",
   "description": "Takes the avg of all activated processes per second over the given time range.",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(zeebe_element_instance_events_total{namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\", action=\"activated\", type=\"PROCESS\"}[1m]))",
     "legendFormat": "{{type}} {{action}}"
    }
   ]
  },
  {
   "title": "Overall FNI  per s [1m]",
   "type": "stat",
   "description": "Flow node instances completed or terminated per second over all partitions.",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(zeebe_element_instance_events_total{namespace=~\"$namespace\", partition=~\"$partition\", pod=~\"$pod\", type!=\"PROCESS\", action!=\"activated\"}[1m]))",
     "legendFormat": "Partition {{partition}} FNI per s"
    }
   ]
  },
  {
   "title": "Completed Processes in avg overtime per sec",
   "type": "stat",
   "description": "Takes the avg of all completed processes per second over the given time range.",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(zeebe_element_instance_events_total{namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\", action=\"completed\", type=\"PROCESS\"}[1m]))",
     "legendFormat": "{{type}} {{action}}"
    }
   ]
  },
  {
   "title": "Completed Tasks in avg overtime per sec",
   "type": "stat",
   "description": "Takes the avg of all completed tasks per second over the given time range.",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(zeebe_element_instance_events_total{namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\", action=\"completed\", type=\"SERVICE_TASK\"}[1m]))",
     "legendFormat": "{{type}} {{action}}"
    }
   ]
  },
  {
   "title": "Process instance creation per second [1m]",
   "type": "graph",
   "description": "Shows the process instance creation rate over all partitions in the namespace. It will only count root process instances, so call activity process instance creations are excluded.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(zeebe_executed_instances_total{namespace=~\"$namespace\", partition=~\"$partition\", pod=~\"$pod\", action=\"activated\"}[1m])) by (namespace)",
     "legendFormat": "Process instance creation {{namespace}}"
    }
   ]
  },
  {
   "title": "Process instance completion per second [1m]",
   "type": "graph",
   "description": "Shows the process instance creation rate over all partitions in the namespace. It will only count root process instances, so call activity process instance creations are excluded.",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(zeebe_executed_instances_total{namespace=~\"$namespace\", partition=~\"$partition\", pod=~\"$pod\", action=\"completed\"}[1m])) by (namespace)",
     "legendFormat": "Process instance creation {{namespace}}"
    }
   ]
  },
  {
   "title": "Job creation per second [1m]",
   "type": "graph",
   "description": "Shows the Job creation rate over all partitions in the namespace",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(zeebe_job_events_total{namespace=~\"$namespace\", partition=~\"$partition\", pod=~\"$pod\", action=\"created\"}[1m])) by (namespace)",
     "legendFormat": "Job creation {{namespace}}"
    }
   ]
  },
  {
   "title": "Job completion per second [1m]",
   "type": "graph",
   "description": "Shows the Job completion rate over all partitions in the namespace.",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(zeebe_job_events_total{namespace=~\"$namespace\", partition=~\"$partition\", pod=~\"$pod\", action=\"completed\"}[1m])) by (namespace)",
     "legendFormat": "Job completion {{namespace}}"
    }
   ]
  },
  {
   "title": "Process Instance Events per second (range = 1m)",
   "type": "table-old",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "sum(rate(zeebe_element_instance_events_total{namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\", type=\"PROCESS\"}[1m])) by (action)"
    }
   ]
  },
  {
   "title": "Job events per second (range = 1m)",
   "type": "table-old",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "sum(rate(zeebe_job_events_total{namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"}[1m])) by (action)",
     "legendFormat": "Stream Processor"
    }
   ]
  },
  {
   "title": "Operate",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Import Time by Type and Partition",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by (type, partition) (rate(operate_import_time_seconds_sum{namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"}[5m])/rate(operate_import_time_seconds_count{namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"}[5m]))",
     "legendFormat": "{{ type }} {{ partition }}"
    }
   ]
  },
  { "title": "Tasklist", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Import Time by Type and Partition",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by (type, partition) (rate(tasklist_import_time_seconds_sum{namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"}[5m])/rate(tasklist_import_time_seconds_count{namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"}[5m]))",
     "legendFormat": "{{ type }} {{ partition }}"
    }
   ]
  },
  { "title": "Optimize", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "Import Time by Type and Partition",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by (RECORD_TYPE, PARTITION_ID) (rate(optimize_import_overallImportTime_seconds_sum{namespace=~\"$namespace\",PARTITION_ID=~\"$partition\",pod=~\"$pod\"}[5m])/rate(optimize_import_overallImportTime_seconds_count{namespace=~\"$namespace\",PARTITION_ID=~\"$partition\",pod=~\"$pod\"}[5m]))",
     "legendFormat": "{{RECORD_TYPE}} {{PARTITION_ID}}"
    }
   ]
  }
 ]
}