apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: camunda
  labels:
    app: kibana
spec:
  ports:
  - port: 5601
  selector:
    app: kibana
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: camunda
  labels:
    app: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
      - name: kibana
        image: docker.elastic.co/kibana/kibana:8.7.1
        # resources:
        #   limits:
        #     cpu: 1000m
        #   requests:
        #     cpu: 100m
        env:
          - name: ELASTICSEARCH_HOSTS
            value: http://dev-elasticsearch:9200
          - name: XPACK_SECURITY_ENABLED
            value: "false"
        ports:
        - containerPort: 5601