global:
  identity:
    auth:
      enabled: true
      publicIssuerUrl: "https://local.distro.ultrawombat.com/auth/realms/camunda-platform"
      operate:
        redirectUrl: "https://local.distro.ultrawombat.com/operate"
      tasklist:
        redirectUrl: "https://local.distro.ultrawombat.com/tasklist"
      optimize:
        redirectUrl: "https://local.distro.ultrawombat.com/optimize"
  ingress:
    enabled: true
    className: "nginx"
    host: "local.distro.ultrawombat.com"
    tls:
      enabled: true
      secretName: camunda-platform

connectors:
  enabled: true
  inbound:
    mode: disabled

# Configure elastic search to make it running for local development
elasticsearch:
  # Request a single node with a persistent volume
  master:
    replicaCount: 1
    persistence:
      size: 15Gi

identity:
  enabled: true
  contextPath: "/identity"
  fullURL: "https://local.distro.ultrawombat.com/identity"

operate:
  enabled: true
  contextPath: "/operate"

optimize:
  enabled: true
  contextPath: "/optimize"

tasklist:
  enabled: true
  contextPath: "/tasklist"

# Reduce for Zeebe and Gateway the configured replicas and with that the required resources
# to get it running locally
zeebe:
  clusterSize: 1
  partitionCount: 1
  replicationFactor: 1
  pvcSize: 10Gi

zeebe-gateway:
  replicas: 1
  ingress:
    enabled: true
    className: "nginx"
    host: "zeebe.local.distro.ultrawombat.com"
    tls:
      enabled: true
      secretName: camunda-platform
