apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: camunda-platform

resources:
- namespace.yaml
- secret.yaml

generators:
- helm-chart.yaml

patches:
- patch: |-
    apiVersion: v1
    kind: Pod
    metadata:
      name: any-test-connection
    $patch: delete
  target:
    kind: Pod
    name: ".*-test-connection"